encoder:
  model_name: "dinov2_vitg14_reg"
  num_trainable_blocks: 6
  return_classtok: true
decoder:
  dec_embed_dim: 768
  dec_num_heads: 12
  dec_depth: 12
  mlp_ratio: 4
masking:
  mask_ratio: 0.9
  patch_size: 14 # based on encoder
augmentation:
  img_res: 322 # 322
train:
  classtoken: true
  random: false
globaldesc:
  dim: 512
eval:
  refinetopcands: 500
  memoryeffmode: false
dataset_locations:
  sfxl: "sf_dataset/raw/train/panoramas"
  gsv: "gsv_cities"
  gldv2: "google-landmark/train"
  msls: "Mapillary_Street_Level_Sequences"
  pitts: "Pittsburgh250k"
  nord: "Nordland"
  tokyo: "Tokyo247/images/test"